# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# ignore all warnings from all dependencies
inhibit_all_warnings!
# ignore warnings from a specific dependency

target 'MandarinUrbanDictionary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MandarinUrbanDictionary
	pod 'SwiftLint'
	pod 'Firebase/Firestore'
	pod 'FirebaseFirestoreSwift'
	pod 'FSPagerView'

end
